# Generated by Django 3.0.6 on 2020-06-18 21:02

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('added_date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(default=datetime.date(2020, 6, 20))),
                ('prize', models.CharField(max_length=100)),
            ],
        ),
    ]
