# Generated by Django 3.0.6 on 2020-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_addcompetition_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompetition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competition/competition_post_images'),
        ),
    ]
