# Generated by Django 3.0.6 on 2020-06-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_addcompetition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompetition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category'),
        ),
    ]
