# Generated by Django 3.0.6 on 2020-06-19 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200619_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompetition',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='addcompetition',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 6, 21)),
        ),
    ]
