# Generated by Django 3.0.6 on 2020-06-22 00:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20200620_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompetition',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
        migrations.CreateModel(
            name='StoryContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=10000)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('likes', models.IntegerField(default=0)),
                ('story_contest_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_contest_name', to='dashboard.AddCompetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='competition/photo_contest')),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('likes', models.IntegerField(default=0)),
                ('photo_contest_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_contest_name', to='dashboard.AddCompetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
