# Generated by Django 3.0.6 on 2020-06-23 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200622_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocontest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storycontest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addcompetition',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 6, 24)),
        ),
    ]
