# Generated by Django 3.0.6 on 2020-06-16 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Photo Contest', 'Photo Contest'), ('Story Contest', 'Story Contest'), ('Meme Contest', 'Meme Contest'), ('Joke Contest', 'Joke Contest')], max_length=100)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(default=datetime.date(2020, 6, 18))),
                ('prize', models.CharField(max_length=100)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
