# Generated by Django 3.0.6 on 2020-06-16 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompetition',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
