# Generated by Django 3.0.6 on 2020-06-22 00:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition_app', '0002_addcompetition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcompetition',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
        migrations.AlterField(
            model_name='addcompetition',
            name='published_by',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
