# Generated by Django 3.0.6 on 2020-06-22 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_app', '0003_auto_20200622_0617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCompetition',
        ),
    ]
